apiVersion: v1
kind: Secret
metadata:
  name: huggingface-credentials
  namespace: vllm-benchmark
type: Opaque
data:
  # Base64 encoded Huggingface token
  token: aGZfSHVMbWtud3NkRFlISkVlZU1DdkNFZFFMb1hVaXVSVVNscQ==