apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-raid-nvme
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany  # Changed from ReadWriteOnce to allow multiple pods access
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/nvme_raid/vllm-data
  nodeAffinity: {}  # Remove node affinity constraints

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: vllm-benchmark
spec:
  accessModes:
    - ReadWriteMany  # Changed to match PV access mode
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-storage

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer