apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-lmcache-membrain
  namespace: vllm-benchmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vllm-lmcache-membrain
  template:
    metadata:
      labels:
        app: vllm-lmcache-membrain
    spec:
      containers:
      - name: vllm
        # Use the new image
        image: 590183691098.dkr.ecr.us-east-1.amazonaws.com/zeus:vllm-membrain2
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 8  # Adjust based on p5.48xlarge configuration
          requests:
            nvidia.com/gpu: 8
            memory: "300Gi"
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: VLLM_USE_V1
          value: "1"
        - name: LMCACHE_USE_EXPERIMENTAL
          value: "True"
        - name: LMCACHE_CONFIG_FILE
          value: "/config/membrain_config.yaml"
        - name: LMCACHE_LOGGING_LEVEL
          value: "DEBUG"
        - name: VLLM_LOGGING_LEVEL
          value: "DEBUG"
        - name: VLLM_CONFIGURE_LOGGING
          value: "1"
        - name: NCCL_DEBUG
          value: "INFO"
        - name: NCCL_IB_DISABLE
          value: "1"
        - name: NCCL_P2P_DISABLE
          value: "1"
        volumeMounts:
        - name: models-volume
          mountPath: "/models"
          readOnly: true
        - name: dshm
          mountPath: /dev/shm
        - name: lmcache-config
          mountPath: /config
        command:
        - "/usr/bin/python3"
        - "-m"
        - "vllm.entrypoints.openai.api_server"
        - "--model"
        - "/models"
        - "--tensor-parallel-size"  # Using TP for large model
        - "4"  # Adjust based on GPU count
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        - "--kv-transfer-config"
        - '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'
        - "--enable-prefix-caching"  # Enable prefix caching
        - "--enable-chunked-prefill"
        - "--uvicorn-log-level"
        - "debug"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "16Gi"
      - name: models-volume
        hostPath:
          path: /mnt/nvme_raid/vllm-data
          type: Directory
      - name: lmcache-config
        configMap:
          name: lmcache-config
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-lmcache-membrain-service
  namespace: vllm-benchmark
spec:
  selector:
    app: vllm-lmcache-membrain
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP